### ISSUE TITLE
Live endpoint doesn't work when source=USD in query string

### ISSUE THREAD

**Issue by chris-skuvault** [apilayer/currencylayer-API#11]
This started happening today when calling the api via https://www.apilayer.net/api/live?access_key="AccessKey"&source=USD&currencies=USD,AUD,MYR,GBP,ZAR,AED,CAD,NZD,SAR,TTD,PKR&format=1 I started to get the following response:

{\n  \"success\":false,\n  \"error\":{\n    \"code\":201,\n    \"info\":\"You have supplied an invalid Source Currency. [Example: source=EUR]\"\n  }\n}"

When calling the same endpoint removing the source= in the query string which defaults to USD then it works fine and is using USD as source. Trying a different source like CAD returns successfully as well. Something seems to have occurred that has caused this endpoint not to work properly anymore

**Comment by ab-petek** [comment]
Any update on this?

**Comment by chrisdone-artificial** [comment]
Yesterday (16 hours ago~):

```
$ curl 'api.currencylayer.com/convert?access_key=...&from=USD&to=GBP&amount=1.0'

{"success":false,"error":{"code":401,"info":"You have entered an invalid \"from\" property. [Example: from=EUR]"}}
```

Today:

```
$ curl 'https://api.currencylayer.com/convert?access_key=...&from=USD&to=GBP&amount=1.0'

{"success":true,"terms":"https:\/\/currencylayer.com\/terms","privacy":"https:\/\/currencylayer.com\/privacy","query":{"from":"USD","to":"GBP","amount":1},"info":{"timestamp":1657597217,"quote":0.84219},"result":0.84219}
```

The service seems to be unstable. It's like they accidentally deleted `USD` for a few hours.

**Comment by chris-skuvault** [comment]
Seems to be working now
