### ISSUE TITLE
Timestamp not rounded

### ISSUE THREAD

**Issue by nii236** [apilayer/currencylayer-API#2]
Upon making an API request with my free account I get the below response.

The timestamp is `1434859633`

Apparently if you convert from unix time to normal time its `Sun, 21 Jun 2015 04:07:13 GMT`. Since I'm on a free account shouldn't the timestamp be round numbers for hours? So it should read `04:00:00 GMT` instead?

```
{
  "success":true,
  "terms":"https:\/\/currencylayer.com\/terms",
  "privacy":"https:\/\/currencylayer.com\/privacy",
  "timestamp":1434859633,
  "source":"USD",
  "quotes":{
    "USDUSD":1,
    "USDAUD":1.286646,
    "USDCAD":1.22655,
    "USDPLN":3.680374,
    "USDMXN":15.347704
  }
}
```

**Comment by apilayer** [comment]
Hi, 

thanks for reaching out. 

While the amount of time exchange rates are cached is identical for all Free & Basic Plan users, the caching periods are individual, depending on when requests are made. 

Example: If your first API request on a particular day is made at 10:25:00 GMT your quotes will be cached for 60 minutes, until 11:25:00 GMT. The next caching period depends on when your next request is made, and so forth. 

This enables us to deliver real-time data even for Free & Basic customers when requesting uncached (not within the 60 minutes after a request) quotes. 

Please let us know here if there is anything else you need clarified, or write us an email at: support@apilayer.net 

Best regards, 

David 
Technical Support

**Comment by nii236** [comment]
Great, thanks for answering!

**Comment by nii236** [comment]
While I'm here, any chance the JSON api can also provide OHLC data instead of just ticker?

**Comment by apilayer** [comment]
At this stage the currencylayer API delivers "midpoint" quotes only.

However, we are definitely interested in extending this spectrum to offer both bid/ask and OHLC data as well. 

Be sure to follow @apilayernet on Twitter and allow us to send you service updates via the currencylayer service. 

Have a nice day! 

David

**Comment by nii236** [comment]
Further to the original issue, if the requests are cached every hour, and I write a script that makes a request every hour, will there not be a chance that I will get the same cached response (since my request might arrive 59:59:59 after the server receives my original request?

I want to make regular hourly checks, but if I have to account for exact one hour caching, I have to add drift into my script, which is undesirable.

**Comment by apilayer** [comment]
Sorry for the slight delay.

The caching time does not amount to exactly 60 minutes, rather around 55 minutes. So you should be good to go using hourly checks. 

Best regards,

Paul 
Technical Support
